USE Hospital_DB

-- Find how many appointments each doctor handled

SELECT 
	gfa.doctor_key,
	gdd.doct_full_name,
	COUNT(gfa.appointment_count) AS total_appointment
FROM gold.fact_appointment gfa
LEFT JOIN gold.dim_doctor AS gdd
ON gfa.doctor_key = gdd.doctor_key
GROUP BY gfa.doctor_key , gdd.doct_full_name
ORDER BY COUNT(gfa.appointment_count) DESC

-- Total Revenue Generated by Each Hospital Branch

SELECT
	hospital_branch,
	SUM(paid_bill_amount) AS total_revenue
FROM gold.fact_billing
GROUP BY hospital_branch
ORDER BY SUM(paid_bill_amount) DESC

-- Number of Patients by Gender
SELECT 
	gender,
	COUNT(*) AS nr_of_patient
FROM gold.dim_patients
GROUP BY gender
ORDER BY COUNT(*) DESC

-- Most Common Treatment Types
SELECT 
	treatment_type,
	SUM(treatment_count) AS treatment_count
FROM gold.fact_treatment
GROUP BY treatment_type
ORDER BY SUM(treatment_count) DESC

-- Appointment Status Distribution
SELECT 
	appointment_status,
	SUM(appointment_count) AS nr_of_status
FROM gold.fact_appointment
GROUP BY appointment_status
ORDER BY SUM(appointment_count) DESC

-- check how many completed and cancelled appointment we have

SELECT 
	SUM(completed_flag) AS completed_appointment,
	SUM(cancelled_flag) AS calcelled_appointment
FROM gold.fact_appointment

-- total amount of pending and completed and unpaid billing amount

SELECT
	SUM(paid_bill_amount) AS revenue_bill_amount,
	SUM(unpaid_bill_amount) AS unpaid_cost_amount,
	SUM(billing_pending_amount) AS pending_cost_amount
FROM gold.fact_billing

        -- paid billied count and unpaid count --
		SELECT 
			SUM(paid_flag) AS paid_billing_count,
			SUM(CASE WHEN paid_flag = 0 THEN 1 ELSE 0 END) AS unpaid_bill_count
		FROM gold.fact_billing
